name: Deploy To Google Play

on:
  push:
    branches: [main]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  distribute:
    name: Distribute bundle to Google Play
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew  
        run: chmod +x gradlew

      - name: Bump versionCode
        run: |
          VERSION_CODE=$(( ${{ github.run_number }} + 100 ))
          echo "New VERSION_CODE=$VERSION_CODE"
          sed -i "s/versionCode = [0-9]\+/versionCode = $VERSION_CODE/" app/build.gradle.kts

      - name: Clean Gradle cache for build
        run: ./gradlew clean

      - name: Assemble Release Bundle
        run: ./gradlew --no-build-cache bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}

      - name: Decode service_account.json
        run: echo "${{ secrets.GOOGLE_PLAY_JSON }}" | base64 --decode > service_account.json

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
         serviceAccountJson: service_account.json
         packageName: com.cybage.androidciproject
         releaseFiles: app/build/outputs/bundle/release/app-release.aab
         track: internal
         status: draft
